### ISSUE TITLE
igi's old todo

### ISSUE THREAD

**Issue by lynxlynxlynx** [lynxlynxlynx/iesdp#17]
- [ ] Add area minimaps to area references
 - [ ] Add worldmap to area references
 - [ ] Add sample animations to Avatar Naming pages
 - [ ] Add CLUA screenshot to CLUA pages
 - [ ] Add spell icons to spell pages
 - [ ] Tokens for IWD1, PST
 - [ ] Detail lightmaps
 - [ ] Actions - link #242 to stats.ids (IWD1, IWD2)
 - [ ] Rewrite triggers (BG1, BG2, IWD1, IWD2, PST)
 - [ ] Improve grammar BCS, DLG, INI
 - [ ] Add missing 2DA files
 - [ ] Label probability 1 and probability 2 as low bound and high bound
 - [ ] Document file precendence: plt -> bam / vef -> vvc -> bam
 - [ ] Document inventory bam sequences: sequence 0 = large, sequence 1 = small
 - [ ] Document disease (IIRC implemented via effect with primary type = 16)
 - [ ] Note the correct slots in IWD2 slots.ids (not just miscx)
 - [ ] Document overlay rain tiles: http://forums.blackw...p?showtopic=805
 - [ ] Document Bit Globals: http://forums.pocket...ic,16931.0.html
 - [ ] Better PLT description - are we the same as NWN: https://web.archive....=article&sid=51
 - [ ] IWD2, use ClassEX not class_ALL
 - [ ] Document the known empty scripting actions
     - [ ] 6 (crash)
     - [ ] 12 (crash)
     - [ ] 32] (empty)
     - [ ] 35 (empty)
 - [ ] PST actions: http://gibberlings3....showtopic=17662
 - [ ] Document the DeathMatch actions
     - [ ] 303 73 82 DeathMatchPositionGlobal(S:Areaname*,P:Dest*,I:Player*)
     - [ ] 304 73 82 DeathMatchPositionArea(S:Areaname*,P:Dest*,I:Player*)
     - [ ] 305 73 82 DeathMatchPositionLocal(S:Areaname*,P:Dest*,I:Player*)
 - [ ] Include the BG1 sound slot info: http://www.blackwyrm.../bsoundsets.php
 - [ ] Document spells removed when importing a character into BG2 (i.e. WIZARD_DELETED / SPWI801)
 - [ ] Document how the 'write magic' button appears (i.e. type = scroll, with 2 extended headers)
